Repository bellingcat/telegram-phone-number-checker, pull requests merged in 2024-02, with the labels that each got.

#15 Match accounts by id instead of username
  pyproject.toml
  telegram_phone_number_checker/main.py
Labels: bug, enhancement

#17 Fix missing info
  pyproject.toml
  telegram_phone_number_checker/main.py
Labels: bug

#19 Updated docstrings and added type hints
  telegram_phone_number_checker/main.py
Labels: documentation
